// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4tNPQR2KdcGm0JEWgjEtetJbyKOgzWHE',
    appId: '1:697334540717:web:35f33c87501565dfb11924',
    messagingSenderId: '697334540717',
    projectId: 'buyka-twitter',
    authDomain: 'buyka-twitter.firebaseapp.com',
    storageBucket: 'buyka-twitter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKnQpnxLhtQx1ks0Yfd5YKqXW36uXhCa8',
    appId: '1:697334540717:android:f8ec68f1a74c6362b11924',
    messagingSenderId: '697334540717',
    projectId: 'buyka-twitter',
    storageBucket: 'buyka-twitter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWAMbUk5j7eebqSSBFHDyIlSXENg64rBc',
    appId: '1:697334540717:ios:7fd7955eb04969ffb11924',
    messagingSenderId: '697334540717',
    projectId: 'buyka-twitter',
    storageBucket: 'buyka-twitter.appspot.com',
    iosClientId: '697334540717-1nee14sp3td7vv7o1rfle0kk7qc3t4s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWAMbUk5j7eebqSSBFHDyIlSXENg64rBc',
    appId: '1:697334540717:ios:7fd7955eb04969ffb11924',
    messagingSenderId: '697334540717',
    projectId: 'buyka-twitter',
    storageBucket: 'buyka-twitter.appspot.com',
    iosClientId: '697334540717-1nee14sp3td7vv7o1rfle0kk7qc3t4s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwitter',
  );
}
